includes:
  - /home/onexadmin/onextel/fluent-bit_api/config/log-paths.yml

env:
  FLUSH_INTERVAL: 15
  LOG_LEVEL: info
  PROMETHEUS_HOST: 0.0.0.0
  PROMETHEUS_PORT: 2020
  REFRESH_INTERVAL: 10
  IGNORE_OLDER: 1d
  METRICS_FLUSH_INTERVAL: 15

service:
  flush: ${FLUSH_INTERVAL}
  log_level: ${LOG_LEVEL}
  parsers_file: /home/onexadmin/onextel/fluent-bit_api/config/parsers.conf

pipeline:
  inputs:
    - name: tail
      path: ${DLR_LOG_PATH}
      tag: dlr_logs
      parser: json
      refresh_interval: ${REFRESH_INTERVAL}
      ignore_older: ${IGNORE_OLDER}

  filters:
    - name: lua
      match: dlr_logs
      script: /home/onexadmin/onextel/fluent-bit_api/lua/process_dlr.lua
      call: process_dlr

    - name: log_to_metrics
      match: dlr_logs
      tag: dlr_metrics
      metric_mode: counter
      metric_name: total_dlr_send
      metric_description: Total number of DLR sends
      label_field:
        - api_key
        - http_resp
        - url
      flush_interval_sec: 15

    - name: log_to_metrics
      match: dlr_logs
      tag: dlr_metrics
      metric_mode: histogram
      metric_name: dlr_response_time_seconds
      metric_description: Distribution of DLR response times
      value_field: response_time
      label_field:
        - api_key
        - http_resp
        - url
      bucket:
        - 0.1
        - 0.5
        - 1.0
        - 3.0
        - 5.0
      flush_interval_sec: 15

  outputs:
    - name: prometheus_exporter
      match: "*_metrics"
      host: ${PROMETHEUS_HOST}
      port: ${PROMETHEUS_PORT}
    
