includes:
  - /home/onexadmin/onextel/fluent-bit_hub/config/log-paths.yml

env:
  FLUSH_INTERVAL: 15
  LOG_LEVEL: info
  PROMETHEUS_HOST: 0.0.0.0
  PROMETHEUS_PORT: 2020
  REFRESH_INTERVAL: 10
  IGNORE_OLDER: 1d
  METRICS_FLUSH_INTERVAL: 15

service:
  flush: ${FLUSH_INTERVAL}
  log_level: ${LOG_LEVEL}
  parsers_file: /home/onexadmin/onextel/fluent-bit_hub/config/parsers.conf

pipeline:
  inputs:
    - name: tail
      path: ${DLVR_ERROR_CODE_LOG_PATH}
      tag: dlvr_error_code_logs
      refresh_interval: ${REFRESH_INTERVAL}
      parser: dlvr_error
      ignore_older: ${IGNORE_OLDER}

  filters:
    - name: lua
      match: dlvr_error_code_logs
      script: /home/onexadmin/onextel/fluent-bit_hub/lua/extract_dlvr_error_code.lua
      call: extract_dlvr_error_code

    - name: log_to_metrics
      match: dlvr_error_code_logs
      tag: dlvr_error_code_metrics
      metric_mode: counter
      metric_name: total_dlvr_error_code
      metric_description: Total number of DLR error codes
      label_field:
        - porter_id
        - code
      flush_interval_sec: 15

  outputs:
    - name: prometheus_exporter
      match: "*_metrics"
      host: ${PROMETHEUS_HOST}
      port: ${PROMETHEUS_PORT}
    
